# Generated by Django 6.0.1 on 2026-01-07 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="contact_form",
            new_name="ContactForm",
        ),
    ]
