# Generated by Django 6.0 on 2026-01-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="city",
            field=models.CharField(default="Delhi", max_length=100),
        ),
    ]
